[package]
name = "scuffle-metrics-derive"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/scufflecloud/scuffle"
authors = ["Scuffle <opensource@scuffle.cloud>"]
readme = "README.md"
documentation = "https://docs.rs/scuffle-metrics-derive"
license = "MIT OR Apache-2.0"
description = "Derive macros for scuffle-metrics."
keywords = ["metrics", "derive", "macros"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
darling = "0.20"
proc-macro2 = "1"
scuffle-workspace-hack.workspace = true

[dev-dependencies]
scuffle-metrics.workspace = true
