name: Release

on:
  push:
    branches:
      - main

env:
  RUST_TOOLCHAIN: nightly

concurrency:
  group: release

jobs:
  crates-io:
    name: Crates.io
    runs-on: ubicloud-standard-8
    environment: crates
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy
          shared-key: clippy
          tools: just,cargo-hakari,release-plz
          cache-backend: ubicloud

      - name: Remove cargo registries
        run: |
          rm -rf ~/.cargo/registry

      - name: Fix workspace deps
        run: cargo +${{ env.RUST_TOOLCHAIN }} xtask workspace-deps

      - name: Cargo Hackari disable
        run: cargo +${{ env.RUST_TOOLCHAIN }} hakari disable

      - uses: fregante/setup-git-user@v2

      - name: Run release-plz
        run: release-plz release --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --git-token ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Docs
    runs-on: ubuntu-24.04
    environment: docs.scuffle.rs
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v7
        with:
          workflow: ci.yaml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: docs
          path: target/doc

      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_DOCS_API_KEY }}
          accountId: ${{ secrets.CF_DOCS_ACCOUNT_ID }}
          command: pages deploy --project-name=scuffle-docrs --branch=main --commit-hash=${{ github.sha }} --commit-dirty=true ./target/doc
